# Numpy Quick Review

## Basic Operation
파이썬 리스트와 numpy 배열과의 차이를 알아 보고 numpy가 제공하는 기본적인 수학 연산을 살펴보자.

In [4]:
import numpy as np

In [31]:
a = np.array(range(10))
print(a)

# ndarray means n-dimensional array
print(type(a))

# element data type
print(a.dtype)

# number of dimensions
print(a.ndim)

# array shape
print(a.shape)

# Bytes per element
print(a.itemsize)

# Bytes of memory used
print(a.nbytes)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
1
(10,)
8
80


In [21]:
x = [1, 2, 3]

for i in x:
    print(i)
    
x = np.array([1, 2, 3])

for i in x:
    print(i)

1
2
3
1
2
3


In [4]:
x = [1, 2, 3]
x.append(4)

# sum is equal to 'append' method of list
x = x + [5]

print(x)

[1, 2, 3, 4, 5]


numpy는 list와는 다르게 '+'는 append 기능을 하지 않는다.

In [5]:
x = np.array([1, 2, 3])
# 'append' and '__sum__' operator do not exit on numpy array

# x.append(4)
x = x + [5]
print(x)

[6 7 8]


In [20]:
# In plain list '__sum__' operator concaterate two operends 
a = [1, 2, 3]
b = [2, 3, 4]

d = a + b
print('list: ',d)

# However, in Numpy '__sum__' operator adds two operends element by element.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

d = a + b
print('np: ', d)

list:  [1, 2, 3, 2, 3, 4]
np:  [3 5 7]


In [1]:
x = [1, 2, 3]
# The plain list doesn't support exponentiation 는 다음과 같은 동작은 정의되어 있지 않다.
# print(x**2)

# 곱하기 동작은 다음과 같이 정의되어 있다.
print(x*2)

[1, 2, 3, 1, 2, 3]


In [7]:
x = np.array([1, 2, 3])

x = x**2
print(x)
x = np.sqrt(x)
print(x)
x = np.log(x)
print(x)
x = np.exp(x)
print(x)

[1 4 9]
[1. 2. 3.]
[0.         0.69314718 1.09861229]
[1. 2. 3.]


## Dot product
내적은 딥러닝을 포함해서 다양한 머신러닝 알고리즘에서 다양하게 사용된다.

In [11]:
a = np.array([2, 2])
b = np.array([2, 1])

# scalar값을 곱할 때는 각 element에 곱이 수행된다.
print(a*2)

# vector간의 element-wise 곱을 수행한다.
print(a*b)

# 내적은 다음과 같이 수행된다.
print(np.sum(a*b))

# 제공되는 dot product는 다음과 같다.
print(np.dot(a, b))
print(a.dot(b))

[4 4]
[4 2]
6
6
6


List를 이용한 dot product와 numpy를 이용한 dot product의 성능 비교를 살펴보자.

In [10]:
from datetime import datetime

a = range(100)
b = range(100)

t0 = datetime.now()

scalar = 0
for i in range(len(a)):
    scalar += (a[i] * b[i])
    
list_duration = (datetime.now() - t0)

print("List: ",list_duration.total_seconds())

# 정규 분포로 부터 랜덤값을 반환한다. 파라미터는 shape을 나타낸다.
# print(np.random.randn(2, 3))

a = np.array(range(100))
b = np.array(range(100))

t0 = datetime.now()

a.dot(b)

np_duration = (datetime.now() - t0)

print("Numpy: ", np_duration.total_seconds())

print("Numpy is faster than list {} times".format(list_duration.total_seconds() / np_duration.total_seconds()))

List:  0.001078
Numpy:  0.000129
Numpy is faster than list 8.356589147286822 times


## Vectors and Matrices

In [11]:
x = np.array([[1, 2], [3, 4]]) 
print(x)
print(x[0])
print(x[0][0])

[[1 2]
 [3 4]]
[1 2]
1


In [12]:
x = np.matrix([[1, 2], [3, 4]])
print(x)
print(x[0])
print(x[0][0])
print(x.T)

[[1 2]
 [3 4]]
[[1 2]]
[[1 2]]
[[1 3]
 [2 4]]


In [13]:
print(np.zeros(5))
# 파라미터가 2개 들어가는 것이 아니라 tuple에 첫 번째 파라미터로 들어간다.
print(np.zeros((3,3)))
# 모든 값이 1로된 array를 반환한다.
print(np.ones((3,3)))
# 0부터 1사이의 값을 반환한다.
print(np.random.random((3,3)))
# 3x3 배열 정규 분포 반환. 입력이 2개 들어간다. 
print(np.random.randn(3,3))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.08164402 0.17594487 0.13263722]
 [0.78408654 0.89737295 0.50260133]
 [0.87232426 0.85581861 0.23590783]]
[[-1.78766205 -1.4111447   0.05526427]
 [-0.83845748  0.16669731 -1.48838359]
 [-0.54618993  0.48382625  0.05239163]]


In [14]:
x = np.random.randn(100,100)
print(x.mean())
print(x.var())

-0.003597299348604
0.9920394466501562


In [15]:
x = np.array([[1,2],[3,4]])
# 역행렬 inverse matrix
i = np.linalg.inv(x)
print(i)
print(x.dot(i))
# determiant
np.linalg.det(x)


[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


-2.0000000000000004

In [16]:
x = np.array([1, 2])
y = np.array([3, 4])

# 외적 outer product
print(np.outer(x, y))

[[3 4]
 [6 8]]


In [17]:
# trace : sum of diagnal values
x = np.array([[1,2],[3,4]])
print(np.diag(x).sum())
print(np.trace(x))

5
5


## Save and Load

저장된 파일의 확장자를 통해서 저장된 데이터 타입을 알 수 있다.

In [18]:
# 파일 확장자가 .npy일 경우, array를 반환한다.
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2, 3])

np.save('./array', x)
data = np.load('./array.npy')
print('x: ', data)

data = np.load('./array.npy', mmap_mode='r')
print('x(mmap_mode) : ', data[1, :])

# 파일 확장자가 .npz일 경우 dictionary 형태의 key-value 형태로 반환된다.
# {filename: array}
np.savez('dict.npz', a=x, b=y)
data = np.load('./dict.npz')
print('a: ', data['a'])
print('b: ', data['b'])


x:  [[1 2 3]
 [4 5 6]]
x(mmap_mode) :  [4 5 6]
a:  [[1 2 3]
 [4 5 6]]
b:  [1 2 3]


## Miscellaneous

In [19]:
data = np.array([[1,2,3], [5,6,7]])

print(data[:,0])
print(data[:,1])
print(data[:,2])

[1 5]
[2 6]
[3 7]
