# Numpy Quick Review

## Basic Operation
파이썬 리스트와 numpy 배열과의 차이를 알아 보고 numpy가 제공하는 기본적인 수학 연산을 살펴보자.

In [21]:
import numpy as np

x = [1, 2, 3]

for i in x:
    print(i)

1
2
3


In [22]:
x = np.array([1, 2, 3])

for i in x:
    print(i)

1
2
3


In [23]:
x = [1, 2, 3]
x.append(4)

# sum is equal to append method of list
x = x + [5]

print(x)

[1, 2, 3, 4, 5]


numpy는 list와는 다르게 '+'는 append 기능을 하지 않는다.

In [27]:
x = np.array([1, 2, 3])
# append and __sum__ operator do not exit on numpy array

# y.append(4)
x = x + [5]
print(y)

[6 7 8]


In [25]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

# sum is equal to a component wise summation
d = a + b

print(d)

[3 5 7]


In [26]:

x = [1, 2, 3]
# list는 다음과 같은 동작은 정의되어 있지 않다.
# print(x**2)

# 곱하기 동작은 다음과 같이 정의되어 있다.
print(x*2)

[1, 2, 3, 1, 2, 3]


In [41]:
x = np.array([1, 2, 3])

x = x**2
x = np.sqrt(x)
# x = np.log(x)
# x = np.exp(x)

print(x)


[ 1.  2.  3.]


## Dot product
내적은 딥러닝을 포함해서 다양한 머신러닝 알고리즘에서 다양하게 사용된다.

In [48]:
a = np.array([2, 2])
b = np.array([2, 1])

# scalar값을 곱할 때는 각 element에 곱이 수행된다.
print(a*2)
# vector간의 곱은 내적으로 수행된다.
print(a*b)

# 내적은 다음과 같이 수행된다.
print(np.sum(a*b))

# 제공되는 dot product는 다음과 같다.
print(np.dot(a, b))
print(a.dot(b))

[4 4]
[4 2]
6
6
6
2.44948974278
