# Tensorflow Tutorial

## A. Graph

In [1]:
import tensorflow as tf 
import numpy as np

상수를 더하기 예제

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)

total = a + b

# tensorboard를 위해 그래프 추가
# 그래프가 완성된 뒤 추가 되어야 한다.
writer = tf.summary.FileWriter('./log', tf.get_default_graph())

with tf.Session() as sess:
    print(sess.run({'ab':(a, b), 'total':total}), '\n')
    
# print(tf.get_default_graph().as_graph_def())    

{'ab': (3.0, 4.0), 'total': 7.0} 



#### tensorboard

* 포트를 특별히 지정하지 않으면, 디폴트 포트는 6006이다.
* tensorboard의 실행 방법은 다음과 같다.

```
$ tensorboard --logdir=<path> --port=6006
```

In [3]:
# tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

# constant of 1d tensor (vector)
a = tf.constant([2, 2], name='vector')

# constant of 2x2 tensor (matrix)
b = tf.constant([[0,1], [2, 3]], name='matrix')

다음과 같이 shape을 지정해서 텐서를 생성한 후, 값을 채울 수 있다.

그래프의 동작 방식을 이해하기 위한 예제이다. 다음은 그래프가 3번 실행 된다.
마지막 실행에서 out1, out2가 동일한 vec값을 사용했다는 점을 확인하기 바란다.

In [4]:
#변수 3개 반환
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2

with tf.Session() as sess:
    print('vec: {}'.format(sess.run(vec)))
    print('vec: {}'.format(sess.run(vec)))
    # out1, out2가 동일한 vec을 사용했다
    print('out: {}'.format(sess.run((out1, out2))))

vec: [0.38927257 0.6899679  0.95704126]
vec: [0.01239777 0.34314167 0.63663936]
out: (array([1.8807906, 1.1670644, 1.1419008], dtype=float32), array([2.8807907, 2.1670644, 2.1419008], dtype=float32))


입력 값을 넣기 위해 placeholder를 추가한 내용이다.

In [5]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

z = x + y
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: 3, y: 4.5}))
    print(sess.run(z, feed_dict={x: [1, 3], y:[2, 4]}))

7.5
[3. 7.]


### Constants

In [6]:
a = tf.constant([[1,2], [3, 4]])
b = tf.zeros([2, 3])
c = tf.ones([2, 3])

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### Variables

* 앞에서 살펴본 tf.constant는 tensor를 반환하는 하나의 함수이다. 하지만 tf.Variable은 여러게의 함수로 구성된 클래스다. (여기 정리해야 함. op, 함수)

* tf.Variable 쓰지 말고 tf.get_variable을 사용하도록 한다.
* tf.constant는 그래프에 상수화되어 저장되지만 Variable은 parameter server에 메모리 상에 저장된다.

### Placeholders

* feed_dict를 사용해 입력 값을 지정하던 방식은 지양하는 것이 좋다.
* 뒤에 설명할 tf.data.Dataset을 이용하는 방법이 좋다.

#### feed_dict을 이용한 디버깅 기법
constant, variable 모두 feedable object로 임의의 값을 지정하여 수식을 확인할 수 있다.

In [ ]:
import tensorflow as tf

batch_size = 3
features = 2
n_hiden = 3

x = tf.placeholder(dtype=tf.float32, shape=[batch_size, features], name='batch_input')

w = tf.get_variable(name='weights', dtype=tf.float32, shape=(features, n_hiden))
b = tf.get_variable(name='bias', dtype=tf.float32, shape=(1, n_hiden))

m = tf.matmul(x, w)
result = tf.add(m, b)

tf.summary.FileWriter('./log', tf.get_default_graph())


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    feed_dict = {
        x: [[1, 2],
            [3, 4],
            [5, 6]],

        w: [[1, 2, 3],
            [3, 4, 5]],

        b: [[10, 10, 10]]
    }

    print(sess.run([m], feed_dict=feed_dict))

## B. Dataset
tensorflow 라이브러리 외부에서 데이터를 가공하여 placeholder에 feed_dict를 이용해서 직접 데이터를 넣어 주는 방식보다 좋은 성능을 가지고 있다.

Dataset을 이용한 입력 소스 지정 방법을 살펴보자

In [ ]:
source = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
])

slices = tf.data.Dataset.from_tensor_slices(source)
# 초기화 필요 없다.
iterator = slices.make_one_shot_iterator()
next_item = iterator.get_next()

with tf.Session() as sess:
    idx = 0
    while True:
        try:
            idx += 1
            print(f'{idx}: ',sess.run(next_item))
        except tf.errors.OutOfRangeError:
            break


In [ ]:
source = tf.random_normal(shape=[10, 3])
slices = tf.data.Dataset.from_tensor_slices(source)
# 초기화 필요. (뒤에서 추가 설명)
iterator = slices.make_initializable_iterator()
next_row = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer)
    
    i = 0
    while True:
        try:
            i+=1
            print(i, sess.run(next_row))
        except tf.errors.OutOfRangeError:
            break

In [ ]:
source = tf.random_uniform([4, 10], minval=0, maxval=100)
# 입력 소스로 부터 dataset을 구성
dataset1 = tf.data.Dataset.from_tensor_slices(source)

print(dataset1.output_types)
print(dataset1.output_shapes)

inputs = tf.random_uniform([4, 100])
labels = tf.random_uniform([4])

# 다른 입력 소스를 묶어서 dataset을 구성
dataset2 = tf.data.Dataset.from_tensor_slices((inputs, labels))

print(dataset2.output_types)
print(dataset2.output_shapes)

# dataset을 묶어서 새로운 dataset을 구성
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

print(dataset3.output_types)
print(dataset3.output_shapes)


In [ ]:
# 딕셔너리를 이용한 입력소스 지정 방법. key에 이름을 부여할 수 있음
sources = dict()

sources['a'] = tf.random_uniform([4])
sources['b'] = tf.random_uniform([4, 100])

dataset = tf.data.Dataset.from_tensor_slices(sources)

print(dataset.output_types)
print(dataset.output_shapes)


### Iterator

iterator 사용 시,range 체크를 반드시 해주는 것이 좋다.

```
try:
    do something
except tf.errors.OutOfRangeError:
    break
```

#### 1. one-shot iterator
* initialization이 필요 없다. (할 수 없다)
* 끝에 도착하면 다시 재활용할 수 없다. 결국, epoch마다 사용 불가능.

In [ ]:
dataset = tf.data.Dataset.range(10)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    while True:
        try:  
          print(sess.run(next_element))
        except tf.errors.OutOfRangeError:
            break

#### 2. initalizable iterator
* 사용전, initialization 필수
* epoch마다 재 활용할 수 있다.
* tf.placeholder를 이용해서 동작을 지정할 있는 장점이 있다.

In [ ]:
max_value = tf.placeholder(tf.int64, shape=[])
dataset = tf.data.Dataset.range(max_value)

iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:

    for epoch in range(2):
        sess.run(iterator.initializer, feed_dict={max_value: 20})
        while True:
            try:
                print(f'epoch {epoch}: ', sess.run(next_element))
            except tf.errors.OutOfRangeError:
                break
            
        print('\n')

#### 3. reinitilizable iterator
* 여러 Data source로 부터 데이터를 가지고 올수 있다. 단, structure은 동일해야 한다.

In [ ]:
training_dataset = tf.data.Dataset.range(10).map(lambda x: x + tf.random_uniform([], -10, 10, tf.int64))
validation_dataset = tf.data.Dataset.range(5)

# reinitializable iterator의 경우는 structure로 정의된다.
# 다른 Data source라 할지라도 같은 데이터 형태를 가지기 때문에 둘 중 하나를 사용하면 된다.
iterator = tf.data.Iterator.from_structure(training_dataset.output_types, training_dataset.output_shapes)
next_element = iterator.get_next()

training_init_op = iterator.make_initializer(training_dataset)
validation_init_op = iterator.make_initializer(validation_dataset)

with tf.Session() as sess:
    
    #The number of epochs
    for e in range(20):
        print(f'> epoch {e}')
        
        # train sequence가 초기화 된다.
        sess.run(training_init_op)
        for _ in range(10):
            print(f'train: {sess.run(next_element)}')
        # validation sequence가 초기화 된다.
        sess.run(validation_init_op)
        for _ in range(5):
            print(f'valid: {sess.run(next_element)}')

#### 4. feedable iterator
* reinitializable iterator와 동일 기능 제공

In [ ]:
# repeat함수를 이용해서 반복되는 sequence를 생성할 수 있다.
# repeat함수를 사용하지 않으면 범위를 벗어날 경우, OutOfRangeError가 발생한다.
training_dataset = tf.data.Dataset.range(10).repeat()
validation_dataset = tf.data.Dataset.range(5)

handle = tf.placeholder(tf.string, shape=[])
iterator = tf.data.Iterator.from_string_handle(handle, 
                                               validation_dataset.output_types, 
                                               validation_dataset.output_shapes)

next_element = iterator.get_next()

training_iterator = training_dataset.make_one_shot_iterator()
validation_iterator = validation_dataset.make_initializable_iterator()


with tf.Session() as sess:
    # input 소스를 선택할 수 있는 핸들러
    training_handle = sess.run(training_iterator.string_handle())
    validation_handle = sess.run(validation_iterator.string_handle())
    
    while True:
        for _ in range(200):
            print('train ', sess.run(next_element, feed_dict={handle: training_handle}))

        sess.run(validation_iterator.initializer)
        for _ in range(5):
            print('valid ', sess.run(next_element, feed_dict={handle: validation_handle}))

In [ ]:
dataset = tf.data.Dataset.range(3)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()
result = tf.add(next_element, next_element)

with tf.Session() as sess:
    sess.run(iterator.initializer)
   
    # 일반적으로 train loop에 사용하는 try-except 블록
    try:
        print(sess.run(result)) # 0
        print(sess.run(result)) # 1
        print(sess.run(result)) # 2
    except tf.errors.OutOfRangeError:
        print('End of dataset')

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(['A', 'B', 'C'])
dataset2 = tf.data.Dataset.from_tensor_slices(([1, 2, 3], ['A1', 'B1', 'C1']))
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

iterator = dataset3.make_initializable_iterator()
next1, (next2, next3) = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer)
    print(sess.run((next1, (next2, next3))))
    # iterator에 묶여 있어서 동시에 다음 element로 넘어간다.
    print(sess.run(next1)) 
    print(sess.run((next1, (next2, next3))))
    
    

### C. Reading input data

#### 1. Consuming NumPy arrays

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([0, 1])

np.savez('./array', features=x, labels=y)
data = np.load('array.npz')

features = data['features']
labels = data['labels']

# The length of features and labels should be the same.
assert features.shape[0] == labels.shape[0]

feature_placeholder = tf.placeholder(features.dtype, features.shape)
labels_placeholder = tf.placeholder(labels.dtype, labels.shape)

dataset = tf.data.Dataset.from_tensor_slices((feature_placeholder, labels_placeholder))
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer, feed_dict={feature_placeholder: features, labels_placeholder: labels})
    print(sess.run(next_element))
    print(sess.run(next_element))

#### 2. Consuming TFRecord data

#### 3. Consuming text data

### D. Preprocessing data with Dataset.map()

#### 1. Parsing tf.Example protocol buffer messages

#### 2. Decoding image data and resizing it

#### 3. Applying arbitrary Python logic with tf.py_func()

### E. Batching dataset elements

#### 1. Simple batching

In [ ]:
inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
# basch 사이즈 지정

batched_dataset = dataset.batch(4)

iterator = batched_dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    print(sess.run(next_element))  # ==> ([0, 1, 2,   3],   [ 0, -1,  -2,  -3])
    print(sess.run(next_element))  # ==> ([4, 5, 6,   7],   [-4, -5,  -6,  -7])
    print(sess.run(next_element))  # ==> ([8, 9, 10, 11],   [-8, -9, -10, -11])

#### 2. Batching tensors with padding

## Layers