In [3]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

/Users/amore/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
seq = np.arange(0, 16)

t = tf.constant(seq)
t = tf.reshape(tensor=t, shape=(2, 2, 2, 2))
print('t:\n', t.eval())
sum0 = tf.reduce_sum(t, axis=0)
sum1 = tf.reduce_sum(t, axis=1)
sum2 = tf.reduce_sum(t, axis=2)
sum3 = tf.reduce_sum(t, axis=3)

print('sum0:\n', sum0.eval())
print('sum1:\n', sum1.eval())
print('sum2:\n', sum2.eval())
print('sum3:\n', sum3.eval())


t:
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
sum0:
 [[[ 8 10]
  [12 14]]

 [[16 18]
  [20 22]]]
sum1:
 [[[ 4  6]
  [ 8 10]]

 [[20 22]
  [24 26]]]
sum2:
 [[[ 2  4]
  [10 12]]

 [[18 20]
  [26 28]]]
sum3:
 [[[ 1  5]
  [ 9 13]]

 [[17 21]
  [25 29]]]
